//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmpSampleSim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmpSampleSim.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tum Fis.
        /// </summary>
        internal static string AllTicket {
            get {
                return ResourceManager.GetString("AllTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar Attirim.
        /// </summary>
        internal static string AmountIncrease {
            get {
                return ResourceManager.GetString("AmountIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod.
        /// </summary>
        internal static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Tutarı.
        /// </summary>
        internal static string BonusAmount {
            get {
                return ResourceManager.GetString("BonusAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasiyer Flag.
        /// </summary>
        internal static string CashierFlag {
            get {
                return ResourceManager.GetString("CashierFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasiyer Index.
        /// </summary>
        internal static string CashierIndex {
            get {
                return ResourceManager.GetString("CashierIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasiyer Isim.
        /// </summary>
        internal static string CashierName {
            get {
                return ResourceManager.GetString("CashierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Ustu.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degistirme.
        /// </summary>
        internal static string Changing {
            get {
                return ResourceManager.GetString("Changing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihle Islem Yap.
        /// </summary>
        internal static string checkBox1 {
            get {
                return ResourceManager.GetString("checkBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamla.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urun sayisi.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisim Index.
        /// </summary>
        internal static string DepartmentIndex {
            get {
                return ResourceManager.GetString("DepartmentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Markasi.
        /// </summary>
        internal static string DeviceBrand {
            get {
                return ResourceManager.GetString("DeviceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Modeli.
        /// </summary>
        internal static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Seri No.
        /// </summary>
        internal static string DeviceSerialNum {
            get {
                return ResourceManager.GetString("DeviceSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirim.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata Cevap Kodu.
        /// </summary>
        internal static string ErrorRespCode {
            get {
                return ResourceManager.GetString("ErrorRespCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Okunamadi :.
        /// </summary>
        internal static string FileCouldntRead {
            get {
                return ResourceManager.GetString("FileCouldntRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uçuş Modu.
        /// </summary>
        internal static string FlightMode {
            get {
                return ResourceManager.GetString("FlightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSM Unique ID Bilgisi.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Tipi.
        /// </summary>
        internal static string groupBox3 {
            get {
                return ResourceManager.GetString("groupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Buyuklugu.
        /// </summary>
        internal static string groupBox4 {
            get {
                return ResourceManager.GetString("groupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum.
        /// </summary>
        internal static string groupBox5 {
            get {
                return ResourceManager.GetString("groupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secenekler.
        /// </summary>
        internal static string groupBox6 {
            get {
                return ResourceManager.GetString("groupBox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonksiyonlar.
        /// </summary>
        internal static string groupBox8 {
            get {
                return ResourceManager.GetString("groupBox8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberlesme Ayarlari.
        /// </summary>
        internal static string groupBox9 {
            get {
                return ResourceManager.GetString("groupBox9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akış.
        /// </summary>
        internal static string handleToolStripMenuItem {
            get {
                return ResourceManager.GetString("handleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log alınması için .INI dosyasındaki HEXLOG 1 olmalıdır..
        /// </summary>
        internal static string HexFileNotFound {
            get {
                return ResourceManager.GetString("HexFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlanmamis Islem.
        /// </summary>
        internal static string IncompleteTransaction {
            get {
                return ResourceManager.GetString("IncompleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖKC&apos;de Tamamlanmamis Islem Var. Islemi IPTAL Etmek için CANCEL, Tekrar Yüklemek için OK&apos;e basin.
        /// </summary>
        internal static string IncompleteTransactionDesc {
            get {
                return ResourceManager.GetString("IncompleteTransactionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Sayisi.
        /// </summary>
        internal static string InstalmentCount {
            get {
                return ResourceManager.GetString("InstalmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Urun.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urun Tablosu.
        /// </summary>
        internal static string ItemTable {
            get {
                return ResourceManager.GetString("ItemTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek Urun.
        /// </summary>
        internal static string JustOneItem {
            get {
                return ResourceManager.GetString("JustOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tutarı :.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilet Tipi : .
        /// </summary>
        internal static string label100 {
            get {
                return ResourceManager.GetString("label100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urun Index :.
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Tipi :.
        /// </summary>
        internal static string label12 {
            get {
                return ResourceManager.GetString("label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisim :.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik No : .
        /// </summary>
        internal static string label14 {
            get {
                return ResourceManager.GetString("label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih 2 : .
        /// </summary>
        internal static string label15 {
            get {
                return ResourceManager.GetString("label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih 1 : .
        /// </summary>
        internal static string label16 {
            get {
                return ResourceManager.GetString("label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eku No :.
        /// </summary>
        internal static string label17 {
            get {
                return ResourceManager.GetString("label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fis No 2 :.
        /// </summary>
        internal static string label18 {
            get {
                return ResourceManager.GetString("label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fis No 1 : .
        /// </summary>
        internal static string label19 {
            get {
                return ResourceManager.GetString("label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tipi :.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifre :.
        /// </summary>
        internal static string label22 {
            get {
                return ResourceManager.GetString("label22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adi :.
        /// </summary>
        internal static string label23 {
            get {
                return ResourceManager.GetString("label23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sube Kodu : .
        /// </summary>
        internal static string label24 {
            get {
                return ResourceManager.GetString("label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Kodu :.
        /// </summary>
        internal static string label25 {
            get {
                return ResourceManager.GetString("label25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik No :.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Kimlik No : .
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura No : .
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Sira No : .
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Tarihi :.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tarihi :.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Saati :.
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade edilecek Bonus miktarı.
        /// </summary>
        internal static string LoyaltyAmountToRefund {
            get {
                return ResourceManager.GetString("LoyaltyAmountToRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fis Kapat.
        /// </summary>
        internal static string m_btn_031 {
            get {
                return ResourceManager.GetString("m_btn_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara Toplam.
        /// </summary>
        internal static string m_btn_032 {
            get {
                return ResourceManager.GetString("m_btn_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Unique ID.
        /// </summary>
        internal static string m_btn_033 {
            get {
                return ResourceManager.GetString("m_btn_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Oku.
        /// </summary>
        internal static string m_btn_034 {
            get {
                return ResourceManager.GetString("m_btn_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasa Odeme.
        /// </summary>
        internal static string m_btn_035 {
            get {
                return ResourceManager.GetString("m_btn_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasa Avans.
        /// </summary>
        internal static string m_btn_036 {
            get {
                return ResourceManager.GetString("m_btn_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Ve Kisim.
        /// </summary>
        internal static string m_btn_039 {
            get {
                return ResourceManager.GetString("m_btn_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasiyer Tablosu.
        /// </summary>
        internal static string m_btn_040 {
            get {
                return ResourceManager.GetString("m_btn_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islemler.
        /// </summary>
        internal static string m_btn_041 {
            get {
                return ResourceManager.GetString("m_btn_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit.
        /// </summary>
        internal static string m_btn_042 {
            get {
                return ResourceManager.GetString("m_btn_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi.
        /// </summary>
        internal static string m_btn_043 {
            get {
                return ResourceManager.GetString("m_btn_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doviz Tablosu.
        /// </summary>
        internal static string m_btn_044 {
            get {
                return ResourceManager.GetString("m_btn_044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeme Iptal.
        /// </summary>
        internal static string m_btn_046 {
            get {
                return ResourceManager.GetString("m_btn_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Iptal.
        /// </summary>
        internal static string m_btn_047 {
            get {
                return ResourceManager.GetString("m_btn_047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iade.
        /// </summary>
        internal static string m_btn_048 {
            get {
                return ResourceManager.GetString("m_btn_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string m_btn_049 {
            get {
                return ResourceManager.GetString("m_btn_049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Unique ID List.
        /// </summary>
        internal static string m_btn_050 {
            get {
                return ResourceManager.GetString("m_btn_050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilet Satis.
        /// </summary>
        internal static string m_btn_051 {
            get {
                return ResourceManager.GetString("m_btn_051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar Arttirim.
        /// </summary>
        internal static string m_btn_052 {
            get {
                return ResourceManager.GetString("m_btn_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar Indirim.
        /// </summary>
        internal static string m_btn_053 {
            get {
                return ResourceManager.GetString("m_btn_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuzde Arttirim.
        /// </summary>
        internal static string m_btn_054 {
            get {
                return ResourceManager.GetString("m_btn_054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuzde Indirim.
        /// </summary>
        internal static string m_btn_055 {
            get {
                return ResourceManager.GetString("m_btn_055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanici Mesaji.
        /// </summary>
        internal static string m_btn_056 {
            get {
                return ResourceManager.GetString("m_btn_056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string m_btn_TicketSale {
            get {
                return ResourceManager.GetString("m_btn_TicketSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string m_btnAddUserMessage {
            get {
                return ResourceManager.GetString("m_btnAddUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Fis.
        /// </summary>
        internal static string m_btnAllTicket {
            get {
                return ResourceManager.GetString("m_btnAllTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Odeme.
        /// </summary>
        internal static string m_btnCashPaymentMenuItem {
            get {
                return ResourceManager.GetString("m_btnCashPaymentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeyi Temizle.
        /// </summary>
        internal static string m_btnClearList {
            get {
                return ResourceManager.GetString("m_btnClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gonder.
        /// </summary>
        internal static string m_btnCompleteUserMessage {
            get {
                return ResourceManager.GetString("m_btnCompleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Dosyası Indir.
        /// </summary>
        internal static string m_btnDownloadBitmapFiles {
            get {
                return ResourceManager.GetString("m_btnDownloadBitmapFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Dosyalarını Al.
        /// </summary>
        internal static string m_btnGetBitmapFiles {
            get {
                return ResourceManager.GetString("m_btnGetBitmapFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek Urun.
        /// </summary>
        internal static string m_btnJustOneItem {
            get {
                return ResourceManager.GetString("m_btnJustOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden Yükle.
        /// </summary>
        internal static string m_btnK_029 {
            get {
                return ResourceManager.GetString("m_btnK_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonksiyon Mesaji.
        /// </summary>
        internal static string m_btnK_030 {
            get {
                return ResourceManager.GetString("m_btnK_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gonder.
        /// </summary>
        internal static string m_btnMatrahsız {
            get {
                return ResourceManager.GetString("m_btnMatrahsız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diger Odeme.
        /// </summary>
        internal static string m_btnOtherPayment_034 {
            get {
                return ResourceManager.GetString("m_btnOtherPayment_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Dosyayı Sil.
        /// </summary>
        internal static string m_btnRemoveBitmapFiles {
            get {
                return ResourceManager.GetString("m_btnRemoveBitmapFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ters(Reverse) Odeme.
        /// </summary>
        internal static string m_btnReversePayment_033 {
            get {
                return ResourceManager.GetString("m_btnReversePayment_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gonder.
        /// </summary>
        internal static string m_btnSendFunctionMessage {
            get {
                return ResourceManager.GetString("m_btnSendFunctionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gonder.
        /// </summary>
        internal static string m_btnSendInvoice {
            get {
                return ResourceManager.GetString("m_btnSendInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string m_btnSendOnCable {
            get {
                return ResourceManager.GetString("m_btnSendOnCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fis Iptal.
        /// </summary>
        internal static string m_btnVoidAllTicket {
            get {
                return ResourceManager.GetString("m_btnVoidAllTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irsaliye.
        /// </summary>
        internal static string m_chcIrsaliye {
            get {
                return ResourceManager.GetString("m_chcIrsaliye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomatic Sale.
        /// </summary>
        internal static string m_chcTaxFreeActive {
            get {
                return ResourceManager.GetString("m_chcTaxFreeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Kapat.
        /// </summary>
        internal static string m_closeHandleMenuItem {
            get {
                return ResourceManager.GetString("m_closeHandleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAGIT FATURA.
        /// </summary>
        internal static string m_cmbInvoiceType_1 {
            get {
                return ResourceManager.GetString("m_cmbInvoiceType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E FATURA.
        /// </summary>
        internal static string m_cmbInvoiceType_2 {
            get {
                return ResourceManager.GetString("m_cmbInvoiceType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E ARSIV.
        /// </summary>
        internal static string m_cmbInvoiceType_3 {
            get {
                return ResourceManager.GetString("m_cmbInvoiceType_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerli Film.
        /// </summary>
        internal static string m_cmbMovieType_1 {
            get {
                return ResourceManager.GetString("m_cmbMovieType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yabanci Film.
        /// </summary>
        internal static string m_cmbMovieType_2 {
            get {
                return ResourceManager.GetString("m_cmbMovieType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tam Bilet.
        /// </summary>
        internal static string m_cmbTicketType_1 {
            get {
                return ResourceManager.GetString("m_cmbTicketType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogrenci Bilet.
        /// </summary>
        internal static string m_cmbTicketType_2 {
            get {
                return ResourceManager.GetString("m_cmbTicketType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirimli Bilet.
        /// </summary>
        internal static string m_cmbTicketType_3 {
            get {
                return ResourceManager.GetString("m_cmbTicketType_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davetli Bileti.
        /// </summary>
        internal static string m_cmbTicketType_4 {
            get {
                return ResourceManager.GetString("m_cmbTicketType_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musteri Avans.
        /// </summary>
        internal static string m_CustomerAdvantageMenuItem {
            get {
                return ResourceManager.GetString("m_CustomerAdvantageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonksiyonlar.
        /// </summary>
        internal static string m_functionsMenuItem {
            get {
                return ResourceManager.GetString("m_functionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiş Başlığı Değiştir.
        /// </summary>
        internal static string m_getSetTicketHeaderMenuItem {
            get {
                return ResourceManager.GetString("m_getSetTicketHeaderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSM Unique ID Al.
        /// </summary>
        internal static string m_getTSMUniqueIDMenuItem {
            get {
                return ResourceManager.GetString("m_getTSMUniqueIDMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID Set Et.
        /// </summary>
        internal static string m_getUniqueIDMenuItem {
            get {
                return ResourceManager.GetString("m_getUniqueIDMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump To ECR (Tekil Odeme).
        /// </summary>
        internal static string m_jumpToECRSinglePaymentMenuItem {
            get {
                return ResourceManager.GetString("m_jumpToECRSinglePaymentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Secenekleri.
        /// </summary>
        internal static string m_langOptMenuItem {
            get {
                return ResourceManager.GetString("m_langOptMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Aç.
        /// </summary>
        internal static string m_openHandleMenuItem {
            get {
                return ResourceManager.GetString("m_openHandleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otopark Fis.
        /// </summary>
        internal static string m_ParkingEntryMenuItem {
            get {
                return ResourceManager.GetString("m_ParkingEntryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Veritabanı.
        /// </summary>
        internal static string m_pluDataBaseMenuItem {
            get {
                return ResourceManager.GetString("m_pluDataBaseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Oku.
        /// </summary>
        internal static string m_pluReadMenuItem {
            get {
                return ResourceManager.GetString("m_pluReadMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF den önce Yazdır.
        /// </summary>
        internal static string m_printBeforeMfMenuItem {
            get {
                return ResourceManager.GetString("m_printBeforeMfMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF Yazdır.
        /// </summary>
        internal static string m_printMfMenuItem {
            get {
                return ResourceManager.GetString("m_printMfMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fis Baslik Yazdir.
        /// </summary>
        internal static string m_printTicketHeaderMenuItem {
            get {
                return ResourceManager.GetString("m_printTicketHeaderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Yazdir.
        /// </summary>
        internal static string m_printTotalMenuItem {
            get {
                return ResourceManager.GetString("m_printTotalMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coklu Mod.
        /// </summary>
        internal static string m_rbBatchMode {
            get {
                return ResourceManager.GetString("m_rbBatchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Haberlesme.
        /// </summary>
        internal static string m_rbSerialConn {
            get {
                return ResourceManager.GetString("m_rbSerialConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekil Mod.
        /// </summary>
        internal static string m_rbSingleMode {
            get {
                return ResourceManager.GetString("m_rbSingleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Satis.
        /// </summary>
        internal static string m_SalePluToolStripMenuItem {
            get {
                return ResourceManager.GetString("m_SalePluToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string m_settingsMenuItem {
            get {
                return ResourceManager.GetString("m_settingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazdaki Unique ID leri Al.
        /// </summary>
        internal static string m_setUniqueIDMenuItem {
            get {
                return ResourceManager.GetString("m_setUniqueIDMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eslesme Baslat.
        /// </summary>
        internal static string m_startPairingMenuItem {
            get {
                return ResourceManager.GetString("m_startPairingMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Vergisiz(TaxFree) Iade .
        /// </summary>
        internal static string m_TaxFreeRefundMenuItem {
            get {
                return ResourceManager.GetString("m_TaxFreeRefundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomatic Sale.
        /// </summary>
        internal static string m_taxFreeTicketMenuItem {
            get {
                return ResourceManager.GetString("m_taxFreeTicketMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Alani 48 karakterden fazla olamaz.
        /// </summary>
        internal static string MessageField {
            get {
                return ResourceManager.GetString("MessageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isim.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Kodu.
        /// </summary>
        internal static string OkCode {
            get {
                return ResourceManager.GetString("OkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orjinal Tutar.
        /// </summary>
        internal static string OriginalAmount {
            get {
                return ResourceManager.GetString("OriginalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odenen.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖKC Üzerinde Ödeme Uygulanaması Bulunamadı.
        /// </summary>
        internal static string PaymentAppNotFound {
            get {
                return ResourceManager.GetString("PaymentAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeme Tablosu.
        /// </summary>
        internal static string PaymentTable {
            get {
                return ResourceManager.GetString("PaymentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu Urun Arama.
        /// </summary>
        internal static string PluItemSearch {
            get {
                return ResourceManager.GetString("PluItemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Tarihi.
        /// </summary>
        internal static string ProcDate {
            get {
                return ResourceManager.GetString("ProcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Sira Numarasi.
        /// </summary>
        internal static string ProcOrderNum {
            get {
                return ResourceManager.GetString("ProcOrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Saati.
        /// </summary>
        internal static string ProcTime {
            get {
                return ResourceManager.GetString("ProcTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre Yukle.
        /// </summary>
        internal static string radioButton01 {
            get {
                return ResourceManager.GetString("radioButton01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Iade.
        /// </summary>
        internal static string radioButton017 {
            get {
                return ResourceManager.GetString("radioButton017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Raporu.
        /// </summary>
        internal static string radioButton02 {
            get {
                return ResourceManager.GetString("radioButton02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iki Tarih Arası Eku Raporu.
        /// </summary>
        internal static string radioButton022 {
            get {
                return ResourceManager.GetString("radioButton022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Iptal.
        /// </summary>
        internal static string radioButton028 {
            get {
                return ResourceManager.GetString("radioButton028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Raporu.
        /// </summary>
        internal static string radioButton03 {
            get {
                return ResourceManager.GetString("radioButton03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali Rapor.
        /// </summary>
        internal static string radioButton04 {
            get {
                return ResourceManager.GetString("radioButton04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eku Rapor.
        /// </summary>
        internal static string radioButton05 {
            get {
                return ResourceManager.GetString("radioButton05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali Kumulatif Rapor.
        /// </summary>
        internal static string radioButton06 {
            get {
                return ResourceManager.GetString("radioButton06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Raporu Gonder.
        /// </summary>
        internal static string radioButton07 {
            get {
                return ResourceManager.GetString("radioButton07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sag.
        /// </summary>
        internal static string radioButton11 {
            get {
                return ResourceManager.GetString("radioButton11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orta.
        /// </summary>
        internal static string radioButton12 {
            get {
                return ResourceManager.GetString("radioButton12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol.
        /// </summary>
        internal static string radioButton13 {
            get {
                return ResourceManager.GetString("radioButton13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cekmece Ac.
        /// </summary>
        internal static string radioButton14 {
            get {
                return ResourceManager.GetString("radioButton14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Gunsonu.
        /// </summary>
        internal static string radioButton15 {
            get {
                return ResourceManager.GetString("radioButton15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Parametresi Yukle.
        /// </summary>
        internal static string radioButton16 {
            get {
                return ResourceManager.GetString("radioButton16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arttirim.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bitleri.
        /// </summary>
        internal static string StatusBits {
            get {
                return ResourceManager.GetString("StatusBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara Toplam.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islem Sonuclari.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi &amp; Kısım.
        /// </summary>
        internal static string tabPage10 {
            get {
                return ResourceManager.GetString("tabPage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme.
        /// </summary>
        internal static string tabPage3_Payment {
            get {
                return ResourceManager.GetString("tabPage3_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinema Bileti.
        /// </summary>
        internal static string tabPage5 {
            get {
                return ResourceManager.GetString("tabPage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel.
        /// </summary>
        internal static string tabPage5_General {
            get {
                return ResourceManager.GetString("tabPage5_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urun No.
        /// </summary>
        internal static string tabPage6 {
            get {
                return ResourceManager.GetString("tabPage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplu Mesaj Modu.
        /// </summary>
        internal static string tabPage6_Batch {
            get {
                return ResourceManager.GetString("tabPage6_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpToECR Opsiyon.
        /// </summary>
        internal static string tabPage7 {
            get {
                return ResourceManager.GetString("tabPage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanici Mes.
        /// </summary>
        internal static string tabPage8 {
            get {
                return ResourceManager.GetString("tabPage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonksiyonlar.
        /// </summary>
        internal static string tabPage9 {
            get {
                return ResourceManager.GetString("tabPage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkur Ederiz.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Indirim.
        /// </summary>
        internal static string TotalDecriment {
            get {
                return ResourceManager.GetString("TotalDecriment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Arttirim.
        /// </summary>
        internal static string TotalIncrement {
            get {
                return ResourceManager.GetString("TotalIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Vergi.
        /// </summary>
        internal static string TotalTax {
            get {
                return ResourceManager.GetString("TotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Iptal.
        /// </summary>
        internal static string TotalVoid {
            get {
                return ResourceManager.GetString("TotalVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Tipi.
        /// </summary>
        internal static string UnitType {
            get {
                return ResourceManager.GetString("UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iadeniz Gerceklesti.
        /// </summary>
        internal static string VoidCompleted {
            get {
                return ResourceManager.GetString("VoidCompleted", resourceCulture);
            }
        }
    }
}
