//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmpSampleSim.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSM_GetUniqueIdIn", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TSM_GetUniqueIdIn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GmpSampleSim.ServiceReference1.Header Header_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public GmpSampleSim.ServiceReference1.Header Header_Info {
            get {
                return this.Header_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Header_InfoField, value) != true)) {
                    this.Header_InfoField = value;
                    this.RaisePropertyChanged("Header_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirmCode {
            get {
                return this.FirmCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmCodeField, value) != true)) {
                    this.FirmCodeField = value;
                    this.RaisePropertyChanged("FirmCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSM_GetUniqueIdOut", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TSM_GetUniqueIdOut : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GmpSampleSim.ServiceReference1.UniqueId UniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GmpSampleSim.ServiceReference1.TsmSign TsmSignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultMessage {
            get {
                return this.ResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMessageField, value) != true)) {
                    this.ResultMessageField = value;
                    this.RaisePropertyChanged("ResultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GmpSampleSim.ServiceReference1.UniqueId UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public GmpSampleSim.ServiceReference1.TsmSign TsmSign {
            get {
                return this.TsmSignField;
            }
            set {
                if ((object.ReferenceEquals(this.TsmSignField, value) != true)) {
                    this.TsmSignField = value;
                    this.RaisePropertyChanged("TsmSign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniqueId", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UniqueId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HexStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Base64 {
            get {
                return this.Base64Field;
            }
            set {
                if ((object.ReferenceEquals(this.Base64Field, value) != true)) {
                    this.Base64Field = value;
                    this.RaisePropertyChanged("Base64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HexStr {
            get {
                return this.HexStrField;
            }
            set {
                if ((object.ReferenceEquals(this.HexStrField, value) != true)) {
                    this.HexStrField = value;
                    this.RaisePropertyChanged("HexStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Bin {
            get {
                return this.BinField;
            }
            set {
                if ((object.ReferenceEquals(this.BinField, value) != true)) {
                    this.BinField = value;
                    this.RaisePropertyChanged("Bin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TsmSign", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TsmSign : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HexStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Base64 {
            get {
                return this.Base64Field;
            }
            set {
                if ((object.ReferenceEquals(this.Base64Field, value) != true)) {
                    this.Base64Field = value;
                    this.RaisePropertyChanged("Base64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HexStr {
            get {
                return this.HexStrField;
            }
            set {
                if ((object.ReferenceEquals(this.HexStrField, value) != true)) {
                    this.HexStrField = value;
                    this.RaisePropertyChanged("HexStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Bin {
            get {
                return this.BinField;
            }
            set {
                if ((object.ReferenceEquals(this.BinField, value) != true)) {
                    this.BinField = value;
                    this.RaisePropertyChanged("Bin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TsmUniqueIDClntWsSoap")]
    public interface TsmUniqueIDClntWsSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TSM_GetUniqueId", ReplyAction="*")]
        GmpSampleSim.ServiceReference1.TSM_GetUniqueIdResponse TSM_GetUniqueId(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TSM_GetUniqueIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TSM_GetUniqueId", Namespace="http://tempuri.org/", Order=0)]
        public GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequestBody Body;
        
        public TSM_GetUniqueIdRequest() {
        }
        
        public TSM_GetUniqueIdRequest(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TSM_GetUniqueIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GmpSampleSim.ServiceReference1.TSM_GetUniqueIdIn input;
        
        public TSM_GetUniqueIdRequestBody() {
        }
        
        public TSM_GetUniqueIdRequestBody(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdIn input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TSM_GetUniqueIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TSM_GetUniqueIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public GmpSampleSim.ServiceReference1.TSM_GetUniqueIdResponseBody Body;
        
        public TSM_GetUniqueIdResponse() {
        }
        
        public TSM_GetUniqueIdResponse(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TSM_GetUniqueIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GmpSampleSim.ServiceReference1.TSM_GetUniqueIdOut TSM_GetUniqueIdResult;
        
        public TSM_GetUniqueIdResponseBody() {
        }
        
        public TSM_GetUniqueIdResponseBody(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdOut TSM_GetUniqueIdResult) {
            this.TSM_GetUniqueIdResult = TSM_GetUniqueIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TsmUniqueIDClntWsSoapChannel : GmpSampleSim.ServiceReference1.TsmUniqueIDClntWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TsmUniqueIDClntWsSoapClient : System.ServiceModel.ClientBase<GmpSampleSim.ServiceReference1.TsmUniqueIDClntWsSoap>, GmpSampleSim.ServiceReference1.TsmUniqueIDClntWsSoap {
        
        public TsmUniqueIDClntWsSoapClient() {
        }
        
        public TsmUniqueIDClntWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TsmUniqueIDClntWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TsmUniqueIDClntWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TsmUniqueIDClntWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GmpSampleSim.ServiceReference1.TSM_GetUniqueIdResponse GmpSampleSim.ServiceReference1.TsmUniqueIDClntWsSoap.TSM_GetUniqueId(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequest request) {
            return base.Channel.TSM_GetUniqueId(request);
        }
        
        public GmpSampleSim.ServiceReference1.TSM_GetUniqueIdOut TSM_GetUniqueId(GmpSampleSim.ServiceReference1.TSM_GetUniqueIdIn input) {
            GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequest inValue = new GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequest();
            inValue.Body = new GmpSampleSim.ServiceReference1.TSM_GetUniqueIdRequestBody();
            inValue.Body.input = input;
            GmpSampleSim.ServiceReference1.TSM_GetUniqueIdResponse retVal = ((GmpSampleSim.ServiceReference1.TsmUniqueIDClntWsSoap)(this)).TSM_GetUniqueId(inValue);
            return retVal.Body.TSM_GetUniqueIdResult;
        }
    }
}
